### ISSUE TITLE
deprecated class should result in deprecated method/val accessors [$50]

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1023]
@ale64bit  If we have a class

```scala
@deprecated("blah", "sometime")
class Foo {
  def bar(): Unit = {}
}
```

then access of

```
new Foo().bar()
```

will result in `Foo` being marked deprecated, but not `bar()`. 

Intuitively I would expect the method to be highlighted as deprecated also. i.e. all members of a class or trait should be marked deprecated.

**Comment by ale64bit** [comment]
mmm, I see. I can work on that, although you will have to let me know a bit more on your intuition. For example, what would be marked as deprecated in the following example?
```scala
@deprecated("blah", "sometime")
class Baz { }
class Foo extends Baz {
  def bar(): Unit = {}
} 
@deprecated("bad", "someday")
object X {
  object Y { def goo(): Unit = {} }
}
object Z {
  X.Y.goo()
}
```
P.S.: As a matter of comparison, IntelliJ doesn't highlights `bar()`, only `Foo()`.

**Comment by fommil** [comment]
Interesting examples. I think all members of a deprecated class or trait should be marked, but if it is inherited then only the members that come from that deprecated interface should be marked deprecated.

So in the above, everything should be strikethrough except `class Foo`, `def bar(): Unit = {}` and `object Z`.

**Comment by fommil** [comment]
i.e. deprecated X implies Y is deprecated, which implies goo is deprecated.

**Comment by ale64bit** [comment]
So, the rule would be like: *a symbol is considered deprecated if (1) it has the deprecation annotation itself or (2) is declared in a class, trait or object considered deprecated*?

Applying it to the above example:
`class Baz` deprecated because of (1)
`class Foo` not deprecated
`extends Baz` deprecated because of (1)
`def bar(): Unit = {}` not deprecated
`object X` deprecated because of (1)
`new Foo()` not deprecated
`.bar()` not deprecated
`object Y` deprecated because of (2)
`def goo(): Unit = {}` deprecated because of (2)
`object Z` not deprecated
`X.Y.goo()` all deprecated because of (2)

I'm a bit afraid that searching for the deprecation annotations will require to traverse up the hierarchy for each symbol, so I hope it will not be a performance hit (I don't think so). Btw, we could introduce two kinds of symbol: one for directly deprecated symbols which is obviously bad and another one for indirectly deprecated symbols (like `goo` and `Y`) which may be less severe. Also, maybe the annotations deserve another highlight since now they get confused with the rest. WDTY?

**Comment by fommil** [comment]
sounds good, if it impacts performance at all then I'm happy to leave it as it is.

**Comment by fommil** [comment]
We had some spare funds, so I added them to this ticket to say thanks for helping out :smile:

**Comment by ale64bit** [comment]
Wow! Thanks a lot :smile: 
The change was actually very subtle )

**Comment by fommil** [comment]
Awesome!

**Comment by fommil** [comment]
Don't forget to claim.

**Comment by fommil** [comment]
Sorry thought you'd raised a pr already.
