### ISSUE TITLE
Navigating without full name

### ISSUE THREAD

**Issue by alxest** [ensime/ensime-server#1060]
~~~
trait tmp {
  def a2: IndexedSeq[Int]
  def a3: scala.collection.IndexedSeq[Int]
}
~~~
When I inspect type (by ensime-print-type-at-point in emacs) of IndexedSeq in a2, it gives precisely same as a3 (scala.collection.IndexedSeq).
I can navigate to its definition in a3, (by ensime-edit-definition function in emacs) but I fail in a2.
I think it would be more convenient if I can browse symbol's definition without its full name.
Is it possible in principle? Are there some complexity behind this?

**Comment by fommil** [comment]
Hmm, that would imply that type aliases are not working, but we fixed this bug.

Can you please provide a minimal test project on github that displays the bug?

**Comment by alxest** [comment]
@fommil 
OK I will try.

**Comment by fommil** [comment]
We're going through the older bug reports that don't have a reproduction.

Nowadays, we close tickets that look like a known issue or don't provide the details requested by the template (which didn't exist when you reported this). The reason is to improve the quality of our issue tracker and to make it easier for contributors to help.

Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. We are happy to help you write an automated test exhibiting the bug, and discuss ideas on how to fix, read the http://ensime.org/contributing guide for more information.

We will leave this ticket open for a few weeks. If you can confirm it is a bug by giving us a **detailed** reproduction - or let us know that you're working on a fix - we will leave it open for longer.

Please read the http://ensime.org/getting_help guide to understand the steps that are now required prior to submitting a bug report. We recently rewrote almost all the documentation since this bug was initially reported and you might find some useful information in there.
