### ISSUE TITLE
Kind of duplicate Note

### ISSUE THREAD

**Issue by d6y** [ensime/ensime-server#1155]
As [discussed on ensime/ensime-atom](https://gitter.im/ensime/ensime-atom?at=564a07f710f6aea94fddcd44).

It appears that the client is receiving multiple `org.ensime.api.Note`s covering the same error and the same line and column of a file (although different beg and end values).  In Atom that ends up looking like this:

![main scala - users richard developer books essential-slick-code chapter-01 - atom 2015-11-16 08-31-47](https://cloud.githubusercontent.com/assets/102661/11192121/213ead9c-8c97-11e5-989c-194e1745aa1a.png)

**Comment by fommil** [comment]
I can imagine this happens every time the file is type checked

**Comment by rorygraves** [comment]
Typically you would get a clearScalaNotes coming between them though if they are difference PC runs.

**Comment by fommil** [comment]
I'm afraid that's not enough information. Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. http://ensime.org/getting_help/

We have very good documentation at http://ensime.org/contributing/ to help you get started hacking on ENSIME.

**Comment by fommil** [comment]
@d6y guess who has set up template replies in github :stuck_out_tongue_closed_eyes:

**Comment by fommil** [comment]
We're going through the older bug reports that don't have a reproduction.

Nowadays, we close tickets that look like a known issue or don't provide the details requested by the template (which didn't exist when you reported this). The reason is to improve the quality of our issue tracker and to make it easier for contributors to help.

Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. We are happy to help you write an automated test exhibiting the bug, and discuss ideas on how to fix, read the http://ensime.org/contributing guide for more information.

We will leave this ticket open for a few weeks. If you can confirm it is a bug by giving us a **detailed** reproduction - or let us know that you're working on a fix - we will leave it open for longer.

Please read the http://ensime.org/getting_help guide to understand the steps that are now required prior to submitting a bug report. We recently rewrote almost all the documentation since this bug was initially reported and you might find some useful information in there.

**Comment by d6y** [comment]
Thanks - I'll see if I can get some kind of a failing test.

For the record, I've managed to get it down to the following source file as input:

```
$ cat src/main/scala/main.scala
case class Foo(a: aString)
```
(in https://github.com/d6y/ensime-server-1155)

And in the Atom log I see this being sent:

```
outgoing: 000095{"req": {"typehint":"TypecheckFileReq","fileInfo":{"file":"/Users/richard/Developer/tmp/ensime-server-1155/src/main/scala/main.scala"}}, "callId": 8}
```

And the following returned:

```
incoming: {"payload":{"typehint":"ClearAllScalaNotesEvent"}}
incoming: {"callId":8,"payload":{"typehint":"VoidResponse"}}
incoming: {"payload":{"typehint":"NewScalaNotesEvent","isFull":false,"notes":[{"beg":18,"line":1,"col":19,"end":25,"file":"/Users/richard/Developer/tmp/ensime-server-1155/src/main/scala/main.scala","msg":"not found: type aString","severity":{"typehint":"NoteError"}}]}}
2 x incoming: {"payload":{"typehint":"NewScalaNotesEvent","isFull":false,"notes":[{"beg":18,"line":1,"col":19,"end":18,"file":"/Users/richard/Developer/tmp/ensime-server-1155/src/main/scala/main.scala","msg":"not found: type aString","severity":{"typehint":"NoteError"}}]}}
incoming: {"payload":{"typehint":"FullTypeCheckCompleteEvent"}}
```

Any hints as to existing unit tests I might get inspiration from to try to reproduce a failing test?

**Comment by fommil** [comment]
great !

try the https://github.com/ensime/ensime-server/blob/master/core/src/it/scala/org/ensime/core/RichPresentationCompilerSpec.scala or thereabouts? Possibly better in https://github.com/ensime/ensime-server/blob/master/core/src/it/scala/org/ensime/core/SemanticHighlightingSpec.scala

**Comment by fommil** [comment]
it'll also typecheck when you save the file, so that could also be the cause if you're saving the file a lot.

I wonder if perhaps the source file watcher should be disabled from talking to the analyser, that could be the cause of the bug here and if that's the case, your test is perhaps best in https://github.com/ensime/ensime-server/blob/master/core/src/it/scala/org/ensime/intg/BasicWorkflow.scala as it is a bit closer to a dev environment.

**Comment by hardmettle** [comment]
Hi @d6y , are you still facing this problem? If yes then can you please give a bit more details about it?
