### ISSUE TITLE
update and improve / consolidate all documentation

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1186]
Since the great big split into modules, the documentation is really complex.

There is a lot of shared content that is editor agnostic (e.g. ensime-sbt, workflow, server side developer docs etc) but intro to new users should be editor specific.

The big question is: do we put the docs all in one location or try to split them across multiple wikis? Probably the former is preferable (less confusing), then we could close down the specific wikis and point everybody at the one place. It might be best to have this independent of `ensime-server` to avoid tickets being raised there automatically. A new repo called `ensime-docs` maybe? No issue tracker, just a brief README, and all the wiki pages.

I would advocate using the wiki for all docs and the READMEs should direct there. This avoids releases on trivial doc changes.

We also need to update our COC to point to TypeLevel's one since we are now a member :smile: http://typelevel.org/

**Comment by fommil** [comment]
https://github.com/ensime/ensime-docs

**Comment by noelmarkham** [comment]
Ok, so I've been having a think about the best way to lay out the documentation for the whole of ENSIME, and I think this makes sense to me:

 * Update both ensime.github.io and ensime.org, to point to a nice, concise one-pager, effectively answering "What is ENSIME, how do I get it, and how do I get going with it for my editor." Off the top of my head, something similar to http://brew.sh/ or http://ohmyz.sh/ would go down nicely I think. 
 * Link from that page to the root documentation repo - that repo can include a reference and context to Sam and Rory's Scala Days slides (the current root of ensime.github.io), and also a link to the video for the slides. Can also point to the more recent talks from 2015's Scala Exchange and their slides.
 * Incidentally, I think every editor repo (ensime-emacs/vim/atom/sublime etc) should have their own "getting started" doc so that anyone arriving on that page can get going with little friction.
 
My [highly scientific poll](https://twitter.com/noelmarkham/status/679923054609346560) earlier this week suggests that using Markdown/Org from a README is preferable to a Wiki - I have no real preference, but considering you can link to the wiki from a README anyway - and using a wiki allows for Sam's comments about releases for trivial doc changes, then I'd suggest going for that.

Thoughts?

**Comment by fommil** [comment]
Good thinking!

We now have a dedicated repo for the documentation, so we can use it for either pages or a wiki. I do have a preference towards wikis because it is easier to create a structure around it and it's easier for people to contribute to.

Agree that all editors/projects should have their own getting started page, but I'd recommend that it be in the docs repo and that all our projects have a standardised "click here to get started" link in their README that directs people to the relevant doc page.

**Comment by fommil** [comment]
@aemoncannon can you please point `ensime.org` at `ensime.github.io` ?

**Comment by fommil** [comment]
@aemoncannon ! Ping

can you please point `ensime.org` at `ensime.github.io` ?

**Comment by fommil** [comment]
we can now track this under the ensime.github.io repo
