### ISSUE TITLE
Support directories in referenceSourceRoots

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-server#1239]
At some point, referenceSourceRoots used to support directories. It would be nice to support this again. That way, you could work on multiple projects and jump between them (rather than jumping to a read-only unpackaged version from a src jar, which creates redundant entries in the buffer list) even if they aren't set up as multi-project builds (a common situation).

**Comment by fommil** [comment]
why don't you just set those dependent projects up as modules in your `.ensime`? See my PR that will add support for `exportJars` (supported in `ensime-sbt` already)

**Comment by fommil** [comment]
this is related to #761 ... if we do this I'd like it to be done as part of that work (which would require a very small change on the client side)

**Comment by fommil** [comment]
we should definitely do this because it is the obvious way to support generated sources... I know @VlachJosef was encountering problems with that (btw, how has your 3 pronged problem been working out? Can you post any more details of the bug? Keen to help since you've contributed so much already!)

**Comment by VlachJosef** [comment]
@fommil generated sources are already supported by `gen-ensime` command. It turns out that plugin what generated these sources for me put them in wrong folder and thus sources haven't been pick up by ensime.

Instead of
`target/scala-2.11/src_managed/main`
they have been put into 
`target/scala-2.11/src_managed`

Anyway what worries me more is that I cannot navigate to these sources without opening that source file first or by using `C-c C-c -C-a`. I'm looking into this issue to understand why and if it can be somehow addressed.

**Comment by fommil** [comment]
@VlachJosef yeah, but what @greenrd is suggesting here is that they are treated as reference sources, not **live** sources.

Can you please create a ticket (which we can use as an epic) for the bugs you encountered around this?

**Comment by VlachJosef** [comment]
@fommil so I've created issue #1244 describing my problem with `src_managed`

**Comment by fommil** [comment]
you know what, this is trivially fixed by #761
