### ISSUE TITLE
turn all TODO / FIXME in the ensime-server codebase into tickets here

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1280]

**Comment by asznajder** [comment]
Due to the Scala Hackathon in Warsaw, I'm going recently through _ensime-server_ code. I probably won't be able to change all FIXME/TODO into tickets, but it would be natural for me to open the issues for those that I'll find. 

One question only: should I remove FIXME/TODO comments as an issue is created for them or do you prefer to leave them?

**Comment by fommil** [comment]
Remove :-)

**Comment by fommil** [comment]
Actually sometimes it might make sense to leave a comment saying that there is a related ticket
