### ISSUE TITLE
emacs ensime-import-type-at-point doesn't seem to like scalaz disjunction (\/)

### ISSUE THREAD

**Issue by caoilte** [ensime/ensime-server#1308]
### Steps to reproduce

1. Using Emacs/Ensime open a project with scalaz as a dependency
2. Declare a scalaz disjunction type eg `val x = String \/ String`
3. Move cursor over `\/` and execute `ensime-import-type-at-point`

### Expected behaviour

I would expect it to either bring up the standard choose an import popup or to error because it couldn't find a type at that point

### Actual behaviour

nothing at all happens (including in the ensime logs)

### Errata

Ensime works fine for me when importing normal types

(I originally mistakenly raised this as https://github.com/ensime/ensime-emacs/issues/375)

I could provide a sample project, but this seems like a really trivial problem, but let me know and I can easily enough.

**Comment by fommil** [comment]
thanks for padding out the example, but I still don't really understand it because I don't use scalaz.

The best thing to do would be to create a failing integration test. You can do this by looking is `SearchServiceSpec` which is using the sources of the `testing/simple` project.

To add scalaz to one of the integration tests, look in `project/EnsimeBuild.scala` but I'd be reluctant to do that (it'll slow down our test cycle) so it would be best if you could create a minimal source-only reproduction by creating some crazy named classes / methods.

The method you want to test is one of the `searchesClasses`.

Going back to emacs for a moment, you might want to read the template on that repo and make sure that you've really studied all the logs that we ask you to create (e.g. `ensime-log-events`).

**Comment by caoilte** [comment]
Thanks for the detailed instructions, I'd be happy to try creating a PR with a failing test.

I'm afraid I'm still new to Emacs/Ensime so I don't know how to find the `ensime-log-events`. The only likely buffer I have is `*inferior-ensime-server-election*` which appears to be the server logs. Nothing gets printed in the `*Messages*` buffer.

**Comment by fommil** [comment]
just execute `(setq ensime-log-events t)` in a scratch buffer before starting up an ensime session and a buffer will appear in the background with every message in / out of the server.

Are you really sure the server didn't see *anything*?

**Comment by caoilte** [comment]
Looks to me like this is a client bug. When I run it on `ArrayBuffer` it `*ensime-events*` prints

```(:swank-rpc
 (swank:import-suggestions "/Users/caoilteoconnor/scala/election/src/main/scala/org/caoilte/election/Election.scala" 933
                           ("ArrayBuffer")
                           10)
 57)
```

But when I run it on `\/` it doesn't print anything.

**Comment by fommil** [comment]
ok, reopen on the client side and try to create a reproduction in `ensime-tests.el`. I suspect we might be back here too.
