### ISSUE TITLE
Check whether SourceMap cannot be created when debug vm is created.

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1375]
`SourceMap` is created in `DebugManager` once at startup - probably makes sense for it to be done each time a debug vm is created. Would be great to test this approach and consider pros and cons.

**Comment by rorygraves** [comment]
This makes the source map pretty useless, it should be regenerated on each fm start.

**Comment by fommil** [comment]
but with @chipsenkbeil's work ongoing, I wonder if we should be bothering to clean up the debugger at this stage?

**Comment by chipsenkbeil** [comment]
I wouldn't yet.

**Comment by fommil** [comment]
@chipsenkbeil do you mind have a quick search of the tracker and just close all tickets regarding the debugger that you think your refactor is going to address?

**Comment by chipsenkbeil** [comment]
@fommi, yeah, I'll do that soon. Plan is to get everything in place and then run through it with you and @rorygraves to see if there is any cleanup that needs to be done at the same time.

**Comment by fommil** [comment]
my approach is that you can just rewrite the whole thing, just try to keep the same API (we can change it in ENSIME 2.0 so leave notes to yourself or add a second API side-by-side)

**Comment by chipsenkbeil** [comment]
FYI, the update version of the debugger in Ensime server still has a singleton debug actor that has a source map created once when the actor is started. There are two ways to approach this:

1. Have the `DebugActor`get torn down and recreated whenever you shutdown and spin up a new debug session (@rorygraves mentioned this possibility)
2. Have the `DebugActor` create a new instance of the `SourceMap` class whenever a new `DebugAttachReq` is received
3. Update the `SourceMap` class to not cache available sources and instead always reach out to grab the most recent sources (probably a bad idea due to performance)
