### ISSUE TITLE
Fix basic stepping test in DebugTest

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1381]
_"handle basic stepping"_ test in `DebugTest` is currently ignored. This test is broken because step in our case is stepping into the classloader for inner class rather than doing a user visible step.

**Comment by chipsenkbeil** [comment]
@fommil @asznajder, I rewrote the step test in the debugger PR to be a simpler case. Since Ensime is going to use the debugger API for its underlying debug engine, the harder logic (corner cases, etc) should be tested in the debugger API while the Ensime server test just needs to guarantee that the behavior works in one case.

So, I'd say this issue can be closed once that PR is merged.
