### ISSUE TITLE
Remove netbeans

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1412]
I've just realised that the netbeans jars we use are GPLv2 (not GPLv3) and the alternative CDDL licence is not GPL compatible so we are probably in a gray area.

**Comment by fommil** [comment]
actually, I wonder if we are ok with using them at all... I'm not sure we count as an "independent module". @aemoncannon how much value are we getting out of the netbeans libraries anyway? I've been pretty disappointed by the lack of engagement from that community to be honest. How much effort would it be to implement what we're using?

BTW, GPL2 is incompatible with Apache 2.0 so we'd be pretty scuppered even if we weren't GPLv3.

**Comment by fommil** [comment]
("downloading the netbeans universe" is becoming a bit of a common complaint about ENSIME these days, I've noticed... and I do tend to agree)

**Comment by fommil** [comment]
FYI, we can't swap to using Eclipse either, because their licence is also incompatible with us.

**Comment by fommil** [comment]
Damn, it really is incompatible. Totally my bad, I should have seen that.

**Comment by fommil** [comment]
I had a quick look. We barely use netbeans at all, we can totally rip it out, much to the pleasure of all our users.

**Comment by aemoncannon** [comment]
re: how much value are we getting out of the netbeans libraries anyway?
Good question. It actually boils down to a couple helpers in TreeUtilities.java:
pathFor, scopeFor, and maybe one other thing. If we clean-room reimplement those utilities then I _think_ we could drop all of netbeans (hallelujah).

**Comment by fommil** [comment]
this is the last time I ever used the phrase "well it's better than Eclipse" to justify *any* technical decision...

**Comment by fommil** [comment]
@mwielocha I've noticed you're keen on Java support. It's this ticket something we could tempt you into picking up?

**Comment by mwielocha** [comment]
Sure, on it.

**Comment by lukasz-golebiewski** [comment]
I might have a look into this as well. Can this task be somehow split in two parts?

**Comment by fommil** [comment]
@mwielocha @lukasz-golebiewski probably bests if the both of you find some time to chat on the `ensime-server` gitter chat room (or here) and come up with a plan :smile: One possibility is that one person (or both with a screen sharing session) creates a work-in-progress branch that removes NetBeans and creates a stub class (which can be written in Scala) with the features that we need... then you could separate the workload and independently write tests / implementations for the methods.

**Comment by fommil** [comment]
or if we expand the scope of work to be done, how about implementing something like Scalariform for Java code using the Java AST?

**Comment by mwielocha** [comment]
For that we would have to re-write both `CompilationInfo` and `TreeUtilities` to scala, plus, of course, all potential dependencies of those two missing methods mentioned above. I'm guessing that we need to do that anyway, since those are copies of netbeans source code and so they suffer from the same licensing issue, right?
I only had a brief look at all this, was planning on starting implementing this weekend. Not sure how to split that though.

**Comment by fommil** [comment]
Pretty much. I'm not sure we use everything in those classes, it might be better to look at exactly what we use and then start from there. Yes, re licence.

**Comment by aemoncannon** [comment]
CompilationInfo is in keeping with a NetBeans style class, but it's just a
dumb data holder. Nothing really interesting there.
TreeUtilities has quite a bit of logic to do robust pathFor and scopeFor.

Perhaps one person could write nasty tests while the other writes the
behavior? : )

**Comment by mwielocha** [comment]
Ok, I have a version of `JavaCompiler` with scala impl of `CompilationInfo` and `TreeUtilities` methods stubbed: [https://github.com/mwielocha/ensime-server/tree/no_netbeans](url)
I don't think we need extra tests sine `JavaCompilerSpec` already tests for 'find at' functionality and those tests fail for obvious reasons. 
Now for the hard part: re-implementing `pathFor` and `scopeFor`, stay tuned.
I've kept netbeans deps untouched since its gonna be a good guideline for the scala impl.

**Comment by fommil** [comment]
Awesowe stuff.
