### ISSUE TITLE
.scala files in the root directory (script projects) are not supported

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1432]
Solution: you must put your `.scala` files into the standard form of your build tool. Typically this is `src/{main,test}/{scala,resources}/`

**Comment by hedefalk** [comment]
Just thinking:

If:

1) There is a simple way for ensime-sbt to ask the project definition if a sourceDirectory is non-recursive (root) or normal (src/main/scala) and
2) There is only black and white - fully recursive or non-recursive, just one folder as opposed to some blacklist of say root/project or something more complicated.

Could we then propose a non-breaking fix only involving ensime-server and ensime-sbt that just adds a non-recursive-src-roots beside the normal one:

```
:source-roots nil
```

becomes

```
:source-roots nil
:non-recursive-source-roots ("/Users/viktor/dev/projects/projectroot")
```

So if we can do that from ensime-sbt and then also make the change in ensime-server, clients could adapt when they see fit? Not saying that the server change is easy, I have no idea, but I got the feeling that the multiple project nature of this issue was a blocker…?

**Comment by fommil** [comment]
Hmm, yeah we could do this but it needs client support from all clients. Probably sbt plugin could complain but add this field anyway, resigned.

**Comment by lukasz-golebiewski** [comment]
@fommil This is not a solution, but a mere workaround ;-) What if I cannot move the sources because I do not own the project?

**Comment by fommil** [comment]
symbolic links for all files, or try to fix it in ensime and then realise - 3 months later - how difficult it is to implement. It would touch every major component, in the server client and build tool, because there is an assumption that source directories are source directories and don't contain moving parts like `.class` files.

**Comment by cfraizer** [comment]
IMHO, the message "To ignore this error, customise `ensimeIgnoreSourcesInBase`" is unhelpful. Customize it where?

Couldn't it read, "To ignore this error, add `ensimeIgnoreSourcesInBase := true` to your build.sbt file." 

Or maybe "To ignore this error, assign the appropriate value to the associated key in the relevant file." :-)

**Comment by fommil** [comment]
you can have it say whatever you want, you just need to change it.
