### ISSUE TITLE
add extra info to the completion API endpoint

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1467]
emac has to perform some hacks to be able to do completions, it would be good to add the required info to the endpoint, in addition to what is already there (to not break the other clients).

**Comment by fommil** [comment]
@aemoncannon I see what you meant now about the history behind the completions objects. I think it should be relatively easy to just add all the info the client needs to the completion response, is there any reason why we haven't gone down that route?

**Comment by fommil** [comment]
i.e. add a `TypeInfo` to `CompletionInfo` and mark the `CompletionSignature` as deprecated (we'll remove post 1.0).

**Comment by aemoncannon** [comment]
TypeInfo's are big. It'd probably double or triple the size of the response. That's the main reason. Historically I've tried to minimize what we send in CompletionInfo because it's such a latency sensitive use case. I just couldn't get over the guilt of sending type info with *every* candidate when it's really only needed for the one you select :-\

We used to have get-call-completion-info(type-id) to handle this. You'd follow up with this call after you select a candidate, to get the type info. This works pretty well, but is harder without type ids (maybe you've solved this problem now?). It's also another round-trip right when the user wants things to be instantaneous... so that's a consideration.

**Comment by fommil** [comment]
hmm, might be worth profiling if this slows things down.

**Comment by fommil** [comment]
ok, how about we give this a trial for a few days and see how it goes?

**Comment by fommil** [comment]
I might have some time tomorrow night to update the emacs side to handle this, I got to learn that code quite well looking into this. May as well follow the rabbit hole all the way to the bottom.
