### ISSUE TITLE
add hint if a completion candidate is infix or not

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1475]
currently the clients are deciding using crude rules such as "there is one param-section, it has one parameter, it is one character long and it is not alphabetical" but we can do this on the server and perhaps be smarter about how we decide. See `ensime-company.el` `ensime--yasnippet-complete-action` for where this is currently done.

Would make sense to add this as a boolean flag on the arrow type class.

**Comment by espinhogr** [comment]
Hi guys, I was thinking about this as my first contribution. Doesn't seem to be too hard (at first glance).

**Comment by fommil** [comment]
that'd be great! Start with the contributor guide on the website, and add a flag to the arrow type to indicate (`isInfix` or something) and then work your way through fixing all the compile errors until you hit a point where you need to decide if it is true of false for a given method. Add some tests and that should be it.

Once the server has the support, you could look at using the new API info in whatever client you want.

**Comment by espinhogr** [comment]
Yes, that's what I'm going to try to do. Obviously at the beginning it's like walking in the dark but I'll try to figure out how to walk straight ;-). Thanks for pointing me to the right way for the moment.

**Comment by espinhogr** [comment]
I've been looking into the code to try to understand better the problem and get used to the codebase. As a result of that, I think the `isInfix` flag is better on the `CompletionInfo` class, even though it's true that this flag is used only for ArrowTypes, as a concept I don't think it belongs to the type. This is due to the fact that in order to decide if it's infix or not we can't rely only on the type but also on the name of the symbol (e.g. the method name). This made me think it should belong to the class `CompletionInfo`being a higher abstraction level, this would lead to a better concerns separation in my opinion. What do you think?

**Comment by fommil** [comment]
ok, sounds sensible.

**Comment by jozi-k** [comment]
This also seems like already solved.

**Comment by fommil** [comment]
Yup good catch
