### ISSUE TITLE
Support VS Code's language server protocol

### ISSUE THREAD

**Issue by svenefftinge** [ensime/ensime-server#1498]
As you might know VS Code have published a so called '[language server protocol](https://github.com/Microsoft/vscode-languageserver-protocol)', which is a very well designed set of methods for a ubiquitous protocol. The idea is to support it in other editors as well, so there is effectively more synergy effect for implementers. We are currently working on supporting it in Eclipse Che (editor) and Eclipse Xtext (language server framework).

Please have a look at https://github.com/Microsoft/vscode-languageserver-protocol/wiki/Protocol-Implementations for a growing list of supporting projects. There are some additional works in progress that are not yet listed there.

There is also a Java implementation of the API, which you could use to directly connect to editors using the same protocol. https://github.com/TypeFox/ls-api 
It is on sonatype SNAPSHOTs https://oss.sonatype.org/content/repositories/snapshots/io/typefox/lsapi/io.typefox.lsapi/0.2.0-SNAPSHOT/

**Comment by fommil** [comment]
That's interesting. I think we'd like to have the freedom to provide our own protocol but implementing the VSCode one is certainly interesting. I have asked the Java people to consider doing their work under the banner of ENSIME https://github.com/georgewfraser/vscode-javac/issues/9 perhaps we could define the protocol that way.

**Comment by fommil** [comment]
@hedefalk @d6y  are you aware of all this?

**Comment by fommil** [comment]
it says JSON-RPC... does that mean it's using ancient TCP RPC as the protocol? That's a shame because websockets is idea for this.

Should be easy enough to do, it just needs somebody to step up and do the work.

**Comment by hedefalk** [comment]
@fommil No, I wasn't aware. Need to look it up better.

On a glance it seems very much like a non-mergable approach to what I'm currently working on which is:

* a shared node library for using ensime from any js based editor which contains and abstracts the server protocol via websockets to just js-futures/callbacks: ensime-node/ensime-client
* This is used from ensime-atom and soon ensime-vscode

I knew that there was a language-server approach described here https://code.visualstudio.com/docs/extensions/example-language-server, that moved the stuff off-process, but I haven't come that far yet in ensime-vscode.

I figured I could just hook this into ensime-client/ensime-node. But if I understand it correctly, this will mean we'll have two network indirections :(

I don't think it's a reasonable approach to directly hook ensime-server as a vscode language provider over tcp though.

My preferred way would be to use a programmatic language "server" API in vscode if there is such since we already have the client/server architecture in ensime-node + ensime-server and usage of ensime-node can be in-process since it will be very thin.

**Comment by hedefalk** [comment]
Curious about the javac-based Java support too… How does this work? I didn't even know javac had any "presentation compiler"? IDEA, Eclipse and Netbeans all have built their own, haven't they? I this something new in javac?

**Comment by fommil** [comment]
@hedefalk no, NetBeans is a (very bloated) wrapper around the java tree API. We already have support for this in the ensime server, I should really give you a code walkthrough sometime :-)

Our Java support needs more TLC because not many people use it, but it shares all the indexing with scala so it is quite maintainable.

Developing in Java really needs the passive hint framework though (boilerplate generation, but not things Lombok can already do) and some things the graphpocalypse will give us (dealing with the interface / implementation pattern used by spring).

**Comment by hedefalk** [comment]
@fommil I'd love a walkthrough some day :) For some reason these things have been pretty hard to search for me. You're not coming to Scaladays this year though?

**Comment by fommil** [comment]
nope, just scalaworld and scalasphere for me. I like circles.

**Comment by fommil** [comment]
@rorygraves we should do a walkthrough with @hedefalk some time

**Comment by rorygraves** [comment]
Absolutely!

**Comment by hedefalk** [comment]
I like days. Lots of days with many hours in them.

**Comment by georgewfraser** [comment]
@hedefalk, https://github.com/georgewfraser/vscode-javac works by programatically invoking the implementation of javac in tools.jar. It returns a nice typed parse tree that contains everything you need to do fancy IDE features.

**Comment by aemoncannon** [comment]
@georgewfraser That's more or less what ensime does, too.

**Comment by georgewfraser** [comment]
@aemoncannon How do you guys deal with incremental compilation of Java? I looked at the source and based on my experience you are going to be rereading all the source files every time.

**Comment by fommil** [comment]
@georgewfraser happy to give you a code walkthrough too! You could start by reading the contributing docs at http://ensime.org there is a video of a recent conference talk there. Java support was written by Aemon with netbeans as a library then swapped to raw access by @mwielocha

We have a label to track java things but it isn't comprehensive https://github.com/ensime/ensime-server/labels/Java

I could set up the build to allow for separate java 7 and 8 impls of interfaces.

**Comment by fommil** [comment]
We swapped because of license incompatibilities and also because netbeans is just *huge*

**Comment by aemoncannon** [comment]
@georgewfraser We never compile all source. We just compile the code the user touches and keep recompiling that as an 'active set'. Everything else is assumed to be on classpath. We have .class/.jar watchers which will suck up new artifacts if you have continuous compilation in your build.

**Comment by georgewfraser** [comment]
Thanks @aemoncannon, I have a lot more questions but I feel like I'm hijacking this thread, I'll take @fommil up on the offer to walk through the code.

Regarding the vscode language server protocol, I have used it extensively and @svenefftinge implementation, ls-api. The language server protocol is excellent but very tied to vscode's model. If you want to support vscode, https://github.com/Microsoft/vscode-languageserver-node and https://github.com/TypeFox/ls-api give you both the client and server implementation so it's ridiculously easy to connect the complete vscode API to a java process.

Having said that, since ensime already has its own protocol, it wouldn't be that hard to just write a vscode client for it in typescript. The only question is whether some features of vscode might not map easily onto the ensime protocol.

**Comment by fommil** [comment]
@georgewfraser I think this has become the main focus of this thread now, so please do continue! :smile:

We support multiple protocols at present (S-Expression and JSON variants over raw TCP or WebSockets) and could add more, but as @hedefalk points out we could put in a shim to do a translation layer if that makes sense (this could even be inside the server code).

Our setup in scala make it incredible easy to change the protocol... all the marshalling happens by magic and is derived from the data model at compile time. We wouldn't need something like `ls-api` for example (this is really just a scala over java win).

**Comment by fommil** [comment]
an option for an external shim would be something that converts between our protocol and uses `ls-api` to communicate with vscode. If we do it inside the ensime-server directly, I'd encourage

I'm not against adding another protocol into the server. The reality is that each of our existing clients is already using a different version of the protocol. The important thing is that the various wire formats is defined by a shared data model so that we don't have to write lots of custom service code for each protocol.

**Comment by georgewfraser** [comment]
I think shimming is going to be harder than you think, the vscode protocol has semantics like "when the user clicks this action, invoke X vscode command". Maybe I'm misunderstanding you but it's not a question of JSON vs S-expression, it's a question of what the messages mean. If you're planning to stick to the semantics of the ensime protocol, you might as well just skip the language server protocol and write a vscode extension in typescript that opens a websocket to ensime.

**Comment by fommil** [comment]
we could add extra endpoints to the protocol to facilitate vscode, depends how complex they are... but there is going to be a lot of shared endpoints with what is already there and that's where a shim would be useful (whether in or outside the server).

**Comment by georgewfraser** [comment]
OK, well I'll just point you to the resources that I found helpful in understanding the vscode API / protocol:

https://code.visualstudio.com/Docs/editor/editingevolved describes the UI features that are supported by the API.
https://code.visualstudio.com/docs/extensionAPI/vscode-api#_languages describes the typescript API of vscode. The language server protocol is basically the same thing, serialized to JSON and sent back and forth over a socket.
https://github.com/Microsoft/vscode-languageserver-protocol/blob/master/versions/protocol-1-x.md describes the messages in the language server protocol.

**Comment by georgewfraser** [comment]
Since I have @fommil blessing, returning to the topic of "using javac as a presentation compiler," I'm interested to understand how incremental ensime is. 

Suppose a user edits Main.java, which imports Other.java. The first time ensime runs, it will have to recompile both Main.java and Other.java, and fetch everything else from the classpath. 

What happens when the user edits Main.java again? Does it recompile Other.java as well?

**Comment by aemoncannon** [comment]
And we're assuming Other.java is not present in compiled classpath?

In this situation we would never compile Other.java. Main.java would should compilation errors as a result. Once you actually visit Other.java (I think even just opening the file), it will be added to the active set which should fix the errors in Main.

Not exactly user-friendly :-) but this scheme scales beautifully to massive projects (which was a motivating use case for me).

**Comment by georgewfraser** [comment]
OK so once the user opens Other.java, it will get compiled, Other.class gets added to the output directory target/, which is on the classpath. Then, when you open Main.java, it will read target/Other.class and get type information from there. Right?

**Comment by fommil** [comment]
Yeah we don't think of ensime as an ide. We consider that kind of stuff to be the job of the build tool and then make it easy to integrate it client side.

**Comment by georgewfraser** [comment]
Does this mean you reread these class files every time, or are they in a "hot cache" somehow?

**Comment by fommil** [comment]
all the java code is in here https://github.com/ensime/ensime-server/tree/2.0/core/src/main/scala/org/ensime/core/javac 

this is the code that recieves the inbound protocol messages https://github.com/ensime/ensime-server/blob/2.0/core/src/main/scala/org/ensime/core/JavaAnalyzer.scala#L53-L82

the api is defined in the api module, which should be referenced from the contributing docs, sorry if the scala is all confusing but hopefully it reads reasonably well. https://github.com/ensime/ensime-server/tree/2.0/api/src/main/scala/org/ensime/api

**Comment by aemoncannon** [comment]
@georgewfraser RE: cache, the StandardFileManager does caching internally. I'm not sure the details but it makes a huge difference to hold onto one manager rather than recreating.

**Comment by fommil** [comment]
@georgewfraser @svenefftinge I'd be happy to do a code walkthrough and general chat today about all of this today on https://meet.jit.si/ (which I just discovered and I'm extremely happy about it)

**Comment by fommil** [comment]
btw @svenefftinge your use of Eclipse Public License is incompatible with ENSIME and any GPL application, so I will refrain from looking at its sources unless you could please change it.

**Comment by svenefftinge** [comment]
@fommil I will be travelling the next couple of days, but we can for sure dual-license the code. I would pick MIT as the second one. Does that work for you?

**Comment by svenefftinge** [comment]
Also having a chat would be great, but I could make it next Friday earliest.

**Comment by vossad01** [comment]
I just found that @dragos appears to have an implementation at https://github.com/dragos/dragos-vscode-scala

**Comment by dragos** [comment]
Yeap, I'm fine to move that into ensime-server at some point. It's not mature enough (doesn't support the full protocol)

**Comment by fommil** [comment]
LOL, yeah, because all the stuff on the ensime organisation all works :stuck_out_tongue_closed_eyes:

**Comment by dragos** [comment]
HA, that's one thing, but the other is that I enjoy the monorepo honeymoon: I can easily change the "API" and immediately use it in the client, no need of publishing, and the change can be done in only one repo.

**Comment by fommil** [comment]
LOTFL because ensime-server follows that rule too... the philosophy around here is if you follow dev you fix it when it breaks.

**Comment by fommil** [comment]
I think this is done now, right?

**Comment by kat-co** [comment]
I couldn't find the relevant commit/PR. Is it possible to get that linked here?

Is it now possible to use ensime as a backend for something like [this](https://github.com/emacs-lsp/lsp-mode)?

**Comment by fommil** [comment]
@kat-co http://ensime.org/editors/vscode/

oooh, that lang server plugin for emacs looks interesting. You need to launch the server + Iulian's language server to get it to work but it would be very interesting to get feedback on it.

**Comment by kat-co** [comment]
Ah, OK so just so I'm on the same page (as well as future people coming across this closed issue): nothing was done in ensime. Iulian, in [this](https://github.com/dragos/dragos-vscode-scala) repo, implemented an ensime -> language-server-protocol shim. So any directions on how to get that running should be taken up on that repo?

Also, please consider reorienting discussion of this work from "VS Code" to "language-server-protocol". VS Code is one such consumer of this, but not the only one. Several editors may want to support clients for this protocol (e.g. emacs), and folks are probably more interested in support for the protocol than VS Code, specifically.

**Comment by fommil** [comment]
Yes exactly, although there has been some talk of moving it into this server. We have a Google summer of code project adding ensime support to scastie, via LS, so there may be activity in this area over the next 3 months.

**Comment by kat-co** [comment]
Ooh, cool! That'd be really awesome if the protocol were supported in ensime directly. Richard Stallman is pushing for support of this protocol in gcc as well, so it might well become the standard way emacs interops between language backends.

Thanks for the info and conversation :)

**Comment by fommil** [comment]
@kat-co omg, wow! That is a huge turnaround for him. Have you got an email or something on that? @rorygraves @dragos if it's good enough for RMS it's good enough for ensime.

**Comment by kat-co** [comment]
Yep:

- [Interest](https://lists.gnu.org/archive/html/emacs-devel/2017-04/msg00367.html)
- [Intent](https://lists.gnu.org/archive/html/emacs-devel/2017-04/msg00741.html)
- [Latest](https://lists.gnu.org/archive/html/emacs-devel/2017-04/msg00798.html) (I think?)

**Comment by fommil** [comment]
I told him about this 2 years ago, he obviously wasn't paying attention. He was utterly uninterested when he realised scala wasn't a lisp.

**Comment by mickaelistria** [comment]
By "this", I guess you mean ensime, right? The LSP specification was
initiated 1.5 years old and have started to be known outside of Microsoft
about a year ago. I think the interest of RMS (and many others) is in
supporting the protocol itself, not much in the particular implementations;
if ensime supports the protocol then it integrates painlessly with
editors/IDEs that support it too - it's an immediate win/win.
At some point, given how well things are going for the LSP, supporting it
in official SDK would be almost a key factor of succes for languages as it
makes fast and easy to support the language in most editors/IDEs.
From ensime perspective, I believe you'd have to support the LSP directly
inside ensime server or package in order to provide the best user and
developer experience. Some other "language-specific servers" such as
OmniSharp are following that path of adopting and enabling the
language-agnostic LSP with a simple `--lsp` flag on server startup. That's
IMO a good pattern.

**Comment by fommil** [comment]
ensime has had an over the wire protocol since the beginning. That entire concept was new to RMS at the time (he hadn't heard of SWANK or SLIME). He's not great at listening, he's usually just broadcasting, I'm glad somebody got through to him.

**Comment by mickaelistria** [comment]
> ensime has had an over the wire protocol since the beginning.

The difference is the ensime's protocol is ensime-specific, whereas LSP is language-agnostic. That's the reason why the 2nd is so successful (6 serioys IDEs/editors supporting it, more than 25 languages providing bindings).

> That entire concept was new to RMS at the time (he hadn't heard of SWANK or SLIME)

Now you're focusing on Emacs support for Scala just like you were focusing on VSCode a few days ago. The idea with the Language Server Protocol is that when ensime implements it, many tools (additionally to VSCode) can consume it without effort.

IMO, the best path forward for ensime is to include @dragos Scala Language Server in Ensime directly to make it more accessible and to consider polishing the language server implementation. Then you'd get almost immediate support for VSCode, Eclipse IDE, Eclipse Che, Atom, Emacs, NeoVim, Monaco, Gnome-Builder (andthe list if growing) that would consume Ensime through the standard-ish Language Server Protocol.

**Comment by mickaelistria** [comment]
I see #1780 was opened to track that. Cool.

**Comment by fommil** [comment]
@mickaelistria I do not expect you to know what we did and did not talk about, so I will elaborate. Part of the discussion was on wire protocols for various languages that Emacs already supported, including cross-language protocols like SWANK (with implementations for common lisp, some niche lisps, R, Java and Scala) as well as the clojure protocol. His attitude has changed dramatically as he was uninterested in anything that used an external process at the time, even if if was GPL, and he was particularly concerned about GPL compilers exposing any form of information over a wire protocol lest it allow proprietary systems to gain access to internal details. I'm very pleased that he has reached a conclusion and I hope a gcc contributor steps forward... it was looking like `clang` was going to dominate.

The language server only has a very basic list of commands, there are limitations for Scala which benefits from custom protocol messages (and integration with the `sbt` build tool). That said, it may well be possible to codify those features in the LS, but I seriously doubt that any editor will be able to support them without additional dev work. I also don't see how the LS does asynchronous messaging, which we have used to great effect.

FYI, we have never considered the LS to be just for vscode. There are ongoing discussions to add support for IntelliJ.
