### ISSUE TITLE
rethink SourceFileInfo

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1566]
when pairing with @hardmettle on #761 we concluded that our modelling of source files could be better. That PR will introduce

```scala
sealed trait EnsimeFile
case class ArchiveFile(archive: Path, entry: Path) extends EnsimeFile
case class RawFile(file: Path) extends EnsimeFile
```

but we could extend this to replace all uses of `File` and `SourceFileInfo` in the API

```scala
case class LiveFile(real: Path, tmp: Path) extends EnsimeFile
case class LiveMemoryFile(real: Path, contents: String) extends EnsimeFile
```

which is much cleaner. We could keep the SWANK protocol the same, but support this naturally in SWANKY and JERKY.

**Comment by hardmettle** [comment]
@fommil Came across `def askLinkPos(sym: Symbol, path: AbstractFile): Option[Position]` in `RichPresentationCompiler.scala` . This is being called at `ModelBuilders.scala` to locate symbol position while mapping over `LineSourcePosition` s .It is needs an `AbstractFile` which was earlier created easily since LineSourcePosition had `file` instead of `EnsimeFile` . I tried adding 
`def getAbstractFile:AbstractFile = ???` in `ensimefile` but looks like there is a dependency problem since I can't seem to import `scala.tools.nsc.io` . How can I work around this ?

**Comment by fommil** [comment]
Don't add code to api, add it to the util file we were working on. Can you please push your branch? I'm blocked until you do that.

**Comment by fommil** [comment]
Oh sorry read it wrong, i think we can maybe add a utility to the core somewhere. Or at the scala compiler to the utils deps.

**Comment by hardmettle** [comment]
Pushed the branch , and apart from that I did not understand the solution you suggested above .

**Comment by fommil** [comment]
Just pattern match on EnsimeFile like you've been doing to pull out the File reference

**Comment by hardmettle** [comment]
How to deal with `FileObject`s coming from `FqnSymbol` (via the `EnsimeVFS`). We need to extract an `EnsimeFile` from them(`FqnSymbol`) in `ModelBuilders` to create `LineSourcePosition` objects.
Note: Earlier we were extracting `Path` since `LineSourcePosition` took that as a parameter.

**Comment by fommil** [comment]
@dragos pointed out in https://github.com/ensime/ensime-server/pull/1612 that he is using an in-process ensime server, which means that the `String` variant is better. So in light of that, I'm closing this ticket because the benefit of turning `(Option, Option)` into a sealed family is very low compared to the disruption to all the clients.
