### ISSUE TITLE
use presentation compiler to demangle debugging symbols

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1735]
as discussed at scalasphere, we should be using a custom profile 

Apologies @chipsenkbeil, I've forgotten what you showed me on how we'd implement this. I had grand illusions of being able to do this at the hack day, but never got that far. Now my short term memory of the event has been nuked. Was the recommendation to create custom implementations of `StructureConverter`?

**Comment by chipsenkbeil** [comment]
You would want to create your own profile that either inherits from [JavaDebugProfile](https://github.com/ensime/scala-debugger/blob/master/scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/java/JavaDebugProfile.scala) or [Scala210DebugProfile](https://github.com/ensime/scala-debugger/blob/master/scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/scala210/Scala210DebugProfile.scala). See the latter for how we extend  the pure Java debug support with custom logic for Scala 2.10/2.11/2.12.

**Comment by strobe** [comment]
@fommil could you add here some additional context about that "scalasphere" discussion?

**Comment by fommil** [comment]
basically the scala-debugger has a bunch of heuristics for converting FQN names of classes / methods into things that make sense in scala language (in the debugprofile). But we don't need to rely on crude guesses in ensime when we can load the files into the PC and resolve them using the `FqnToScalaName` etc utilities. There are quite a lot of these `XtoFqn` or `FqnToX` converters in the code, all with tests (I hope) to show usage.

**Comment by strobe** [comment]
thanks.
seems is enough to start.

**Comment by fommil** [comment]
some good code to look at would be the tests for the fqn converters. And then, separately, the demangling code in scala-debugger.

**Comment by strobe** [comment]
I got some understanding of XtoFqn/FqnToX things and heuristics at scala-debugger, but I still don't know that is the input source of debugging symbols (by which I may test resolving via PC). 
Is it a DebugLocateNameReq at incoming.scala or something else?

**Comment by fommil** [comment]
cool!

it's more like an internal call in the DebugActor to the debugger itself, although we probably expose it to the user (the whole debugger API could benefit from a rewrite along with the UI).

@chipsenkbeil probably knows better

**Comment by strobe** [comment]
sorry, Im very slowly moving with this thing, because I just view that code from time to time at rare free evenings. But anyway I got few questions below.

`DebugActor` has few cases for requests like `DebugToStringReq` (which used `location` or/and `threadId` information), those cases used `lookupValue` method (which resolving ValueInfo by using debugger ScalaVirtualMachine (directly or via cache)). Most of requests to VM called with info like debuger object id, field name, thread id (things which mostly has a sense for debugger).

On the other side at Analyzer we have things like `FqnOfSymbolAtPointReq` which can ask PC for something like FQN/Symbol by using `file` and `poin`.

Therefore it looks like I have to figure out way to convert something like threadID&location to
file&point and then I will able to replace VM calls with requests to PC via Analyzer.
But I'm not sure that it's that you need - My assumption is correct? or you need
something different here - may be it needs to include Debug*Req redesign too.

**Comment by fommil** [comment]
you can go deeper than the protocol layer. You can use the internal support for converting between bytecode fqn and scala name. You don't need the position in a source file to do that. Of course, you might decide to add a protocol message to support that via actors.
