### ISSUE TITLE
import type at point not working for objects

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1771]
possibly a regression in #1769 @hzenginx it seems that import suggestions no longer work for `object`. I noticed this when trying to follow https://github.com/ensime/ensime-server/issues/1770#issuecomment-299314401 (but for `CreateRunSpec` not `Clock`) and noticed that import-type-at-point wasn't doing anything.

Maybe we are no longer stripping the final `$`? Mabye this has always been broken.

Maybe we should just do the search on the scala name now that we have the graphpocalypse instead of hacking it with bytecode fqn manipulation...

**Comment by hzenginx** [comment]
do we know this was working before? 
I tried to revert the camelcase commit locally and assembled jar to test and it was still not working.

**Comment by fommil** [comment]
Probably broken since forever.

**Comment by jozi-k** [comment]
The issue root cause is [this line](https://github.com/ensime/ensime-server/blob/893196d7931b8e54c4a83555c80175c95e07654a/core/src/main/scala/org/ensime/core/Indexer.scala#L29) in Indexer.
I am bit puzzled what does "old" mean there, nor I understand why would we strip all classes which ends with $/$class. The quick fix would be to delete the filter for $, but I have strange feeling it exists for some reason. Any comments on this @fommil ?

**Comment by fommil** [comment]
from memory, I think this was to duplicate legacy behaviour. The problem is that almost everything has a companion and it ends up in lots of false positives. For import type at point, we want to include `object` but strip the `$`. Actually we really want to search by scala name, which is now possible (I think) in the graph.

**Comment by fommil** [comment]
maybe instead of exclude these, we could `.replaceAll` followed by `.distinct`?
