### ISSUE TITLE
integrated language server support

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1780]
As pointed out by @kat-co in https://github.com/ensime/ensime-server/issues/1498#issuecomment-303555186 Emacs may get improved language server support, so perhaps we should provide it for as many things as possible instead of our custom protocol (or in addition to).

Would also be of immediate benefit to vscode @dragos and scastie and I know @rorygraves is keen.

We should still aim not to introduce any more Scala binary deps.

**Comment by dragos** [comment]
I'm happy to donate my work, but it does have Scala dependencies (my own LSP implementation, based on [scala-json-rpc](https://github.com/dhpcs/scala-json-rpc).

**Comment by fommil** [comment]
Cool. I wouldn't want another json library so if it's yet another json marshaller then we need to port it to spray-json

**Comment by mickaelistria** [comment]
> instead of our custom protocol (or in addition to).

In addition to would probably be better as the LSP may have some limitations your current protocol hasn't, and keeping the current current custom protocol would make existing integrations backward compatible (whereas dropping it would break all existing integrations).
FYI, OmniSharp (which is like Ensime but for C#) does enable the LSP instead of their own custom protocol by adding a `--lsp` flag when invoking the server. I think it's a good approach that would be fine for ensime too.

I suggest you also consider using Eclipse LSP4J Java library which allows to easily write language server just by implementing a couple of APIs. Resources:
* https://projects.eclipse.org/projects/technology.lsp4j
* https://www.eclipse.org/community/eclipse_newsletter/2017/may/article2.php
A simple way to get started with it is
```java
LanguageServer server = new EnsimeLanguageServer();
Launcher<LanguageClient> launcher = LSPLauncher.createServerLauncher(server, input, output);
server.setClient(launcher.getRemoteProxy());
launcher.startListening();
```
and then to properly implement the EnsimeLanguageServer class. This adds dependencies to Guava, and XBase library (a utility library used by the XText language). The addition footprint isn't that high. If you prefer to avoid it anyway in regular Ensime you could consider using a different main/binary for the LSP part, so there could be an `ensimeRunMain` and and `ensimeLspRunMain`.

**Comment by dragos** [comment]
I haven't look at it in detail, but it sounds like the Eclipse LSP4J is the better option. At the time I started playing with the LSP I didn't know about the Eclipse implementation. I agree with @fommil that we need to limit the number of Scala dependencies (scala-json-rpc is based on play-json).

**Comment by fommil** [comment]
it's a no-go https://github.com/eclipse/lsp4j/blob/master/LICENSE

It should be trivial to port scala-json-rpc to spray-json (or circe, which I am increasingly preferring). I'd be happy to accept a PR using this lib and then we can port later.

**Comment by fommil** [comment]
There's an argument that we should pull spray-json and spray-json-shapeless into ensime too, since both are a pain to release for new versions of scala.

**Comment by mickaelistria** [comment]
> it's a no-go https://github.com/eclipse/lsp4j/blob/master/LICENSE
>

See
https://github.com/ensime/ensime-server/issues/1498#issuecomment-223794750
. The authors offered to dual-license the code if it can help project such
as Ensime to adopt it and to easier ship support for LSP.

**Comment by fommil** [comment]
@mickaelistria I have a terrible memory. OK, I guess that could help, but if it's using runtime reflection, I'd rather we stick to the typeclass approach of the above scala library and maintain an internal fork.

**Comment by fommil** [comment]
FYI I tweeted out this thread, let's hope we get some contributors, it's a very exciting concept! https://twitter.com/fommil/status/867320939872235521

**Comment by yyadavalli** [comment]
@fommil I can take this up, once I am done with #1346. I am close to completing the typeclass derivation for HOCON.

**Comment by fommil** [comment]
That'd be awesome but I don't see any rush :-)

**Comment by yyadavalli** [comment]
Hi @dragos, whenever you have time, can you please move `ensime-lsp` into its own repo. I can port it to use `circe` and then into `ensime-server`

**Comment by fommil** [comment]
spray-json :-P

**Comment by fommil** [comment]
@yyadavalli we now have a fork of `spray-json` in the server under the `json` module, it'd definitely be best to use that instead of any other JSON library, and we have netty so it should be ideal for any socket handling.

**Comment by kat-co** [comment]
Hey all, what's the current status of this?

**Comment by yyadavalli** [comment]
The sponsored student it currently working on it. You can follow the latest pull requests for more detailed progress info.

**Comment by kat-co** [comment]
Awesome! Would it be possible to cc #1780 on the PRs to make it easier to track status?

**Comment by yyadavalli** [comment]
I have no idea how to do that

**Comment by fommil** [comment]
I think it just needs that string added and github does the rest.

**Comment by fommil** [comment]
Btw @vovapolu is doing the work and I'm sure he'd appreciate any input or advice on the protocol.

**Comment by kat-co** [comment]
Yep, you just have to put a pound-sign/hashtag and then the number of the ticket and GitHub will auto-magically link things together. It's not a big deal if @vovapolu can't; I just thought I'd ask :) Thanks for your contributions @vovapolu!

**Comment by adelbertc** [comment]
Can we consider this fixed by https://github.com/ensime/ensime-server/pull/1882 ?

**Comment by fommil** [comment]
I think so, but they haven't been merged yet... @vovapolu should be able to give a better estimate.

In any case it's taking longer than expected so the rewrite of the vscode / atom clients may not happen before we run out of cash.

**Comment by vovapolu** [comment]
:tada: I almost merged basic LSP support. It works in vs-code, but it's only a subset of whole LSP protocol. 
I'm going to write atom plugin and then continue to extend LSP module.

**Comment by laughedelic** [comment]
> I'm going to write atom plugin and then continue to extend LSP module.

@vovapolu do you have any progress on this already? If not much, I have an idea: I made an Atom plugin for the Scalameta-based language server and I just realised that it could support the ENSIME-based server too: https://github.com/laughedelic/atom-ide-scala/issues/1#issuecomment-343320728. What do you think about it?

**Comment by fommil** [comment]
@laughedelic what's the scalameta server?

**Comment by laughedelic** [comment]
@fommil here: https://github.com/scalameta/language-server

**Comment by laughedelic** [comment]
By the way, check these messages on Gitter:
* in [scalameta/scalameta](https://gitter.im/scalameta/scalameta?at=5a0352c432e080696e7ee359)
* and in [scala/tooling-contrib](https://gitter.im/scala/tooling-contrib?at=5a046928614889d4755cf2cb) which is suggested to be a common chat for this topic

**Comment by vovapolu** [comment]
>https://github.com/scalameta/language-server
lol, I see they use @dragos code, that I recently rewrote. Maybe we could combine our efforts? That would be great since I will finish my work on ensime-lsp-server soon and they will be able to continue this project.

**Comment by vovapolu** [comment]
@laughedelic I'm writing my plugin on Scala.js (well, trying to write :) ). It shares some utils code with vscode plugin. Why do you think we should merge our plugins? They're pretty small and some users might be confused with two (almost) independent implementations of LSP in one plugin.

**Comment by laughedelic** [comment]
> I'm writing my plugin on Scala.js (well, trying to write :) ). It shares some utils code with vscode plugin.

Oh, I was also going to try to rewrite it in Scala.js 👍 I'm not sure yet what will be the `apm publish` So if you say there is some shared code, do you have already a VS Code plugin implemented in Scala.js?

> Why do you think we should merge our plugins? They're pretty small and some users might be confused with two (almost) independent implementations of LSP in one plugin.

Well, I look at it another way round, I think that users will be more confused with existence of different plugins: "which one should I install? can I install both to try or they will conflict?" 🤔  While you are right that these plugins are quite small and can coexist, I think that from user perspective, it makes more sense to install just one "IDE" plugin for Scala and then choose which server they want to use by default or use different ones depending on the project setup (e.g. presence of the ENSIME config). This is just my opinion, probably it's better to ask users (other than ourselves) to know their perspective 😄

**Comment by mickaelistria** [comment]
How to compose language servers is still an open and complex issue. There
seems to be no universal solution both from IDE and LS perspective.
In thr case of Scala, I have the impression that some efforts should be
done in the Scala community to avoid duplication of efforts rather than
multiplying efforts and dividing results...
That said, I don't imagine a new Scala developer would understand why and
how to choose one server over the other. If doable, it would seem best to
ship multiple compatible Scala LS so user would get an aggregation of
results. Maybe an intermediary "aggregator" LS dispatching messages to all
LS and returning aggregated results would make sense.
FYI, Eclipse IDE support for LSP can map N LS to one given language, so the
aggregation is already in.


-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, at Red Hat Developers <https://developers.redhat.com/> community
Elected Committer Representative at the Eclipse Foundation
<https://www.eclipse.org/org/> board of directors

**Comment by laughedelic** [comment]
@mickaelistria I agree in general about avoiding duplication.

> That said, I don't imagine a new Scala developer would understand why and how to choose one server over the other.

I think it's a responsibility of the editor plugin and/or servers themselves to document well what are the offered features and differences to others. A new Scala developer doesn't care how LSP server is called (or how it works), but cares how well it works for _his projects_. So from my point of view, an editor plugin should let them to try different ones and choose whichever fits better in a user-frienly fashion. Unless, of course, all servers will get merged in a single uber-something, then there is no problem at all 😆 

> If doable, it would seem best to ship multiple compatible Scala LS so user would get an aggregation of results. Maybe an intermediary "aggregator" LS dispatching messages to all LS and returning aggregated results would make sense.

I think that this works out of the box, results from different connected servers will be aggregated in the editor interface. But this will just show users duplicated similar results which is inconvenient and annoying (imagine long completion lists with duplicates).
