### ISSUE TITLE
Debugger StepOverLine not responding properly

### ISSUE THREAD

**Issue by periklis** [ensime/ensime-server#1870]
Over quite sometime @elbaulp discovered that we can't step over to the next line but on only continue debug in ensime-emacs ensime/ensime-emacs#575. I've actually stepped in to debug the emacs-part with edebug by following approach. I am moving this issue from ensime-emacs here in reply to @fommil.

1. First as suggested by the troubleshouting quide i debugged the produced SWANK messages in my editor:
```elisp
(:swank-rpc (swank:debug-continue "1") 2040)

(:return (:ok t) 2040)

(:debug-event (:type breakpoint :thread-id "1" :thread-name "main" :file "/PATH/TO/scala-experiments/src/main/scala/Main.scala" :line 135))

(:swank-rpc (swank:debug-next "1") 2041)

(:return (:ok t) 2041)

(:swank-rpc (swank:debug-continue "1") 2042)

(:return (:ok t) 2042)

(:debug-event (:type step :thread-id "1" :thread-name "main" :file "/PATH/TO/scala-experiments/src/main/scala/Main.scala" :line 136))

(:debug-event (:type threadDeath :thread-id "1"))

(:debug-event (:type threadStart :thread-id "827"))

(:debug-event (:type threadDeath :thread-id "827"))

(:debug-event (:type disconnect))
```

2. The message seem to correspond to the server Swank Specification Format:
```scala
unmarshal(
      s"""(swank:debug-next "13")""",
      DebugNextReq(dtid): RpcRequest
)
```
and there exists none introduced typo since the 1.0 if we diff the branches for
```scala
final case class DebugNextReq(threadId: DebugThreadId) extends RpcDebuggerRequest
```

3. However, after digging into ```DebugActor``` i noticed the following suspect behavior:
- DebugNextReq calls stepOverLine on the scala debugger which returns a Future according to the scaladoc
- Debug Continue calls resume on the scala debugger which returns Unit.
- e.g. http://scala-debugger.org/api/cookbook/stepping-over-a-line-of-code/
```scala
s.stepOverLine(be.thread).foreach(se => {
   val path = se.location.sourcePath()
   val line = se.location.lineNumber

    println(s"Stepped to $path:$line")
    launchingDebugger.stop()
})
```

I suspect that the behavior of not moving to next line has to do with disregarding the Future. The issue manifests also in step-in/out calls. Can someone with scala skills evaluate and propose a fix for this issue, since i am a novice in scala?

Leave this list and include an `x` in the relevant boxes:

- [x] I have read http://ensime.org/getting_help/
- [x] I have followed the troubleshooting guide for my text editor
- [ ] I have asked in http://gitter.im/ensime/ensime-server
- [ ] I have included a link to an example project
- [x] I have included exact bug reproduction instructions

**Comment by chipsenkbeil** [comment]
There could be a bug when a future times out. This is using the high-level implementation, which is found here: https://github.com/ensime/scala-debugger/blob/master/scala-debugger-api/src/main/scala/org/scaladebugger/api/profiles/java/requests/steps/JavaStepRequest.scala#L266

I don't think I've tested what happens when the future times out. I can't remember if a timeout in a future will trigger the failure path or just throw an exception, either.

**Comment by elbaulp** [comment]
Hi, I will be happy to help in what I can. Is there some wiki or how-to debug `ensime-server` and `sbt`. I have no clue on how to begin.

**Comment by periklis** [comment]
@elbaulp http://ensime.org/server/contributing/

**Comment by fommil** [comment]
http://ensime.org/server/contributing

**Comment by chipsenkbeil** [comment]
Yeah, I'd say first step is to try to add a test where a step future times out and figure out the behaviour.

**Comment by periklis** [comment]
any progress on it? If not, i would like to jump in and try me best.

**Comment by elbaulp** [comment]
I am reading through the contribution guidelines to try to help resolve this issue. So far I have never contribute to ensime, but I think this issue is the right one. 

At the end of this week I'll hope I can post any advances with respect this issue.

**Comment by elbaulp** [comment]
Excuse me again. I am running into problems with this.

Trying to debug this issue, I am being unable to start ensime to debug it. This is my current situation:

- I've downloaded ensime 2.0, since ensime 3.0 does not work with emacs.
- I've executed `ensimeConfig` in the directory. 
- Now I'm stuck trying to start the project itself to be able to debug it. My intention was to set a breakpoint in `DebugNextReq` and start from there. But I do not know how to start `ensime` itself from sbt, in order to attach the debugger with `ensime-db-attach`. 

How do I do it? so far I've tried (in the `sbt shell`):

- `run`, `runMain`, `backgroundRun`

all of them fail, the last with this error: 

`background log: error: Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'ensime.config'`

So, my question is, how do you debug ensime itself?

Sorry for my silly questions, but I've spend 1 hour trying without luck.
