### ISSUE TITLE
get the LSP working in some clients

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#1935]
There was some interest at ScalaSphere to maintain and use the LSP support. @rorygraves sounded vaguely interested and I swear I heard him say that @zainab-ali promised to write it all :wink: 

The following people voted to keep the LSP in ensime which, according to the way it works around here, means that they have volunteered themselves to help out:

- @gabro
- @laughedelic
- @wifasoi
- @markusa380
- @gruggiero
- @bonabeavis
- @chipsenkbeil
- @ktonga
- @everson

**Comment by rorygraves** [comment]
Me too - I think this is the way to go.

**Comment by everson** [comment]
oh, I didn't know those were the rules! But now I want to dance accordingly. 💃

**Comment by fommil** [comment]
if the emacs lsp client turns out to be good enough, perhaps we could abandon SWANKY as well. Less stuff to maintain.

**Comment by fommil** [comment]
btw with regards to launching, you may need to edit sbt-ensime to insert the `ensime-lsp` jars into the `.ensime` file.

**Comment by gabro** [comment]
> you've not seen the emacs lsp client 😉 (I have, it's not good)

Maybe, but it's still work that can be delegated and shared across N languages.

Also, Emacs floats around 5-10% adoption according to the latest StackOverlflow survey. Good LSP clients exist for most languages above 25-30% adoption, which would mean targeting a 80-something% of developers. It sounds like a pretty good deal to me ;)

**Comment by laughedelic** [comment]
> The following people voted to keep the LSP in ensime which, according to the way it works around here, means that they have volunteered themselves to help out

Whatevs.. Nobody promised anything so people volunteer as much as they do in fact.

> (e.g. picking up what @vovapolu has done and see whether that can be made server-implementation-agnostic and shared across VSCode/Atom/Sublime/...).
> I know @laughedelic was also interested in this area.

As I claimed before, I am interesting in supporting Ensime LSP server in atom-ide-scala: https://github.com/laughedelic/atom-ide-scala/issues/13, but it's blocked by https://github.com/ensime/ensime-lsp-clients/issues/2. I understand that @vovapolu now doesn't have time to maintain it and I'm glad to contribute some minor fixes/improvements if it will be needed, but someone who owns that repo (@vovapolu or @fommil?) should publish it or something. Even though it's MIT-licensed, I don't want to copy-paste the code or publish it myself.

I'm also interested in helping with other clients which can be extended in JS and reuse this common launcher code.

> Maybe, but it's still work that can be delegated and shared across N languages.

I agree with @gabro that delegating maintenance of the generic LSP client libraries is good. And yes, by having a common JS(/Scala.js) launcher code we can reduce the editor-specific part to just <50 lines of trivial code (just wiring things).

Improving ensime-lsp is just a matter of time: I think if there are any TypeScript/Python/C#/etc. people using it, then it will get improved quickly (because they have good LS and they care about getting good UX with it).

In addition to all this clients-related stuff I want to say that although @fommil [claims](https://github.com/lampepfl/dotty/issues/1523#issuecomment-382367376) that

> ensime has a fully working LSP implementation as of 6 months ago

this is a bit exaggerated. I don't mean to diminish @vovapolu's work, but I think he admitted himself that the LSP server is still a bit unstable and requires quite some work to get to a usable state. I also tried to use it some time ago and noticed some problems and inconsistencies with the protocol. Some of these issues got closed under "Bug Bankruptcy": https://github.com/ensime/ensime-server/issues/1911.

So I think the first step would be splitting LSP part into a separate repo as was decided in https://github.com/ensime/ensime-server/issues/1918#issuecomment-371241057 and restoring known issues that weren't fixed yet.

**Comment by fommil** [comment]
Obviously I'm jesting when I say you've all volunteered to help with this initiative.

I believe it is in the best interests of the Scala community that ensime becomes the MVP LSP server. All the features in the LSP are implemented by ensime-server and have been implemented for [**literally years**](http://ensime.github.io/editors/) (many of these features since 2009). Neither dotty, sbt, metals (or scalaide!) are anywhere near the level of reliability and user adoption of ensime.

The protocol endpoint is all that is needed to be production ready. We can, as a community, do what sbt, dotty and (to a lesser extent) metals have done: write an LSP protocol and then work backwards to the features. Then hit the presentation compiler and user deployment / integration elephants. Or, we can start with ensime-server, integrate all the learning of the innovation in the `*meta*` world, and then have something that everybody can build their clients on top of.

I'm not sure it does make sense to have a separate repo for ensime-lsp. We have that already in https://github.com/dragos/dragos-vscode-scala and if it was working for people then we wouldn't have an LSP-WG to address the gap. Either ensime does LSP, or it does not. If there is an intermediate service, it should be the bus that Rory has been talking about (a manager for scala language servers and build tools) and that can talk to ensime over JERKY. But even this can be developed in the ensime-server codebase to simplify the deployment problem.

**Comment by zainab-ali** [comment]
>  @rorygraves sounded vaguely interested and I swear I heard him say that @zainab-ali promised to write it all 

I'll be careful what I say around @rorygraves now :wink: 

Sure, I'd be happy to work on it!  I've been itching to get the ensime server snapshot working with emacs, and LSP seems like the best option.  

The current implementation is flawed, though I don't know how flawed.  I couldn't test it with emacs as a result of #1911. Is anyone successfully using ensime LSP?

**Comment by rorygraves** [comment]
@zainab-ali I feel I've been misquoted here ;)

**Comment by laughedelic** [comment]
I'd like to clarify the situation with Ensime's JSON-RPC/LSP implementation. I know that it was based on the one found in [dragos-vscode-scala](https://github.com/dragos/dragos-vscode-scala) project, but there it uses [scala-json-rpc](https://github.com/shogowada/scala-json-rpc), while here I don't see this dependency and remember @vovapolu saying something about reimplementing that because of some issues with the original library. Sorry if I mixed up something, please correct me and clarify what is the real situation.

Now we have #1911 which basically breaks Ensime's LSP and @zainab-ali is going to work on a fix: https://github.com/ensime/ensime-server/issues/1911#issuecomment-384250449. But I'm not sure I understand where does this issue originally come from: is it inherited from dragos-vscode-scala or from scala-json-rpc (or its reimplementation)?

In Metals we used dragos-vscode-scala's LSP implementation as well in the beginning and while I remember we had to fix some problems with it, we had it working OK up to the point when it became inconvenient to extend it and https://github.com/scalameta/metals/pull/164 has landed:

> This PR gets rid of the dependency on scala-json-rpc and removes languageserver `LanguageServer/Connection/MessageReader/....` Only simple LSP case classes remain from the languageserver project in addition to the MessageWriter.

This implementation has now become a separate project: https://github.com/scalameta/lsp4s and its dependencies will be minimized to make it more appealing as a drop-in solution for LSP in Scala: https://github.com/scalameta/metals/issues/285.

I suggest that Ensime considers reusing lsp4s instead of maintaining a custom implementation. You can see in Metals that it's very [easy to use](https://github.com/scalameta/metals/blob/a45aa46864c59317fb2d57fa2aedc36ea4921185/metals/src/main/scala/scala/meta/metals/MetalsServices.scala#L222-L243).

**Comment by rorygraves** [comment]
@laughedelic Thanks for the thoughtful response - I agree it makes sense for use to share an implementation.  I had not done my due diligence to check what was already there.

**Comment by fommil** [comment]
That can't be pulled into ensime-server because of the huge dependency chain but would make sense as a separate project.

**Comment by fommil** [comment]
if the current ensime-lsp is going to be too much work, should we just move this initiative into #1941 - set up a fresh repo somewhere, use Alexy's lib, and delete the ensime-lsp?

It would be good to get the BSP stood up and running, even if all it is doing is starting to ensime in a separate process and translating the messages LSP messages to JERKY and back. We could then add sbt server support and build out everything that was discussed.

**Comment by laughedelic** [comment]
> It would be good to get the BSP stood up and running, even if all it is doing is starting to ensime in a separate process and translating the messages LSP messages to JERKY and back.

I don't really see how this is related. BSP is for communicating with build tools, it's not supposed to launch language servers or translating messages between LSP/JERKY/etc.

**Comment by fommil** [comment]
the scala bus, not the bsp.

**Comment by laughedelic** [comment]
#1945 fixes #1911 and makes Ensime LSP _minimally usable_. I see these features working:
* symbols outline (`textDocument/documentSymbol`): shows some symbols, but not all and the hierarchy is broken
* type on hover (`textDocument/hover`): works, but has some glitches (like empty tooltips of showing nonsense when hovering on comments)
* go to definition (`textDocument/definition`): works quite well and even jumps to the stuff from the project deps 👍 
* completions (`textDocument/completion`): seems to work, but symbols are not sorted well (e.g. proper methods should be prioritised over inherited ones)
* diagnostics on type (`textDocument/publishDiagnostics`): works with some delay, but at some point stops working and doesn't reset after you fix errors (most likely because PC just dies ☠️)

There's still plenty to work on to make it usable. But beside the issue mentioned above, I think the most urgent problem is the _shutdown routine_. The server doesn't shutdown properly and you need to kill the process (see this [very old message](https://gitter.im/ensime/ensime-server?at=5a13855d51915d962afc3c30)). 
+ newly launched server fails on trying to access locked cache (so you need to do `rm -rf .ensime_cache`)
+ even when you kill the zombie, new server may fail to launch (needs investigation)

This problem is inherited, we had to fix it in Metals too at some point: https://github.com/scalameta/metals/pull/53.

**Comment by laughedelic** [comment]
And on the client side: I got it working with Atom. It parses `.ensime` and uses it to launch the server. See https://github.com/laughedelic/atom-ide-scala/pull/64 for details.

<img width="1064" alt="screen_shot_2018-04-28_at_06_39_31" src="https://user-images.githubusercontent.com/766656/39392311-c84e1172-4ab3-11e8-998e-28a8e428382a.png">

**Comment by fommil** [comment]
:tada: excellent work! I consider this ticket closed and I think it's up to all the lsp client authors to get together and decide what to do with their projects. I have no preference to the winner.

**Comment by fommil** [comment]
The shutdown stuff should be fixed by moving to metacp. This is orientdb's fault.

**Comment by laughedelic** [comment]
> I consider this ticket closed and I think it's up to all the lsp client authors to get together and decide what to do with their projects

I don't think it's good to close it. We've already gathered here, why not just continue the discussion? There's a lot to discuss both on the clients and on the server sides. I'd like to hear, for example, from @ktonga about his experiments with the Vim client. 

I would also like to see other clients working. Currently the bar for writing clients is quite high: there's no simple launcher for the server (please, don't point again at the undefined and non-existent yet "bus" thing), so clients have to parse `.ensime` to launch it. 

There's also some activity again in the dragos-vscode-scala repo, is there any interest to migrate that client to use the new Ensime LSP server? /cc @dragos 

> The shutdown stuff should be fixed by moving to metacp. This is orientdb's fault.

Besides whatever possible problems with OrientDB there is a purely LSP-specific issue with not handling the `shutdown` request properly (and the `exit` notification), see the linked PR which fixed it in Metals.

**Comment by fommil** [comment]
You can keep discussing here if you want. Feel free to reopen if that makes a difference.

**Comment by fommil** [comment]
There is a python launcher in the sublime code.

**Comment by laughedelic** [comment]
Shutdown problem mentioned above was fixed in #1946. The next issue that breaks Ensime LSP is #1948 which is hopefully easy to fix (for somebody who knows Ensime internals).

**Comment by laughedelic** [comment]
Nope, it's definitely not critical. At least I don't see it causing any problems now.
