### ISSUE TITLE
clean up elisp code to hide internal functions from users

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#419]
a typical lisp convention is to use

```lisp
(defun ensime--this-is-internal ...)
```

double-dash notation for internal functions and variables.

We could do with a mass rename to adhere to this convention. That way it will really clean up `M-x ensime-TAB` completion and make it easier to be sure our documentation is up to date.

**Comment by fommil** [comment]
I don't know why I added a bounty on this. @aemoncannon or @edani if you'd like to claim I'd happily close the ticket.

**Comment by aemoncannon** [comment]
Question: what is an 'internal' function? is it one that a user would not
call interactively? or is it one that we would not expect/want to export
outside of ensime codebase? or is it one that should be private to a
particular module, i.e. file.

For example, should ensime-util functions all have the '--', or should none
of them have it (as they're all used in other modules)?

My gut is that it's any function we don't want to support as part of our
API, but that's pretty much everything ; )

I ask because I'm trying to break completion into a modules by backend.

**Comment by fommil** [comment]
The latter, private.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#148
