### ISSUE TITLE
tab completion does not work correctly for base types

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#516]
e.g. 

``` 5.``` **tab**

Suggests ``` % / + - ```  but does not suggest ```.toString```

**Comment by fommil** [comment]
We're going through the older bug reports that don't have a reproduction.

Nowadays, we close tickets that look like a known issue or don't provide the details requested by the template (which didn't exist when you reported this). The reason is to improve the quality of our issue tracker and to make it easier for contributors to help.

Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. We are happy to help you write an automated test exhibiting the bug, and discuss ideas on how to fix, read the http://ensime.org/contributing guide for more information.

We will leave this ticket open for a few weeks. If you can confirm it is a bug by giving us a **detailed** reproduction - or let us know that you're working on a fix - we will leave it open for longer.

Please read the http://ensime.org/getting_help guide to understand the steps that are now required prior to submitting a bug report. We recently rewrote almost all the documentation since this bug was initially reported and you might find some useful information in there.
