### ISSUE TITLE
Global scalariform settings

### ISSUE THREAD

**Issue by chrisbarrett** [ensime/ensime-server#789]
I have scalariform settings that I would like Ensime to apply to all my projects. Is there a way to provide global formatter settings? 

Currently I'm copying & pasting `:formatter` fields into all the `.ensime`s I create, but there must be a better way!

**Comment by fommil** [comment]
use scalariform-sbt and set your settings there: either per-project or globally, and the ensime-sbt plugin picks them up automatically.

Note that scalariform is in a bit of a mess right now, with people publishing their own artefacts (using the same FQNs as the original!!!!) because the original author has given up. We're trying to get the people involved to come up with a solution.

**Comment by fommil** [comment]
for any other global customisations, use this approach https://github.com/ensime/ensime-server/wiki/Quick-Start-Guide#installing-the-ensime-sbt-plugin

**Comment by chrisbarrett** [comment]
Thanks for the quick reply :+1:
