### ISSUE TITLE
Don’t highlight entire file as errline when presentation compiler crashes

### ISSUE THREAD

**Issue by sellout** [ensime/ensime-server#809]
Whenever the presentation compiler crashes, the entire file gets highlighted as errline with a “presntation compiler crashed” title text. This isn’t particularly helpful.

I would prefer if maybe it just added a special annotation to the mode-line lighter and let scala-mode2 highlight the file normally.

**Comment by fommil** [comment]
yes, that sounds sensible. This should be relatively easy to do, as well. Fancy having a go at implementing this? If so, we can include in 1.0

**Comment by sellout** [comment]
Sure, I’ll take a look today.

**Comment by fommil** [comment]
:smile: to do the modeline thing, you'll need to do emacs client changes. To edit the server side, that's probably in SemanticHighlighting.scala or similar.

**Comment by fommil** [comment]
Probably the best thing you can do is create a minimal integration test that fails (in core) and then work back from there.

**Comment by fommil** [comment]
I see this a lot with https://github.com/fommil/imaginary-friend/issues/11

I can't create a minimal reproduction despite a few attempts.

A `C-c C-c r` usually fixes it, but it's annoying to have to retype. Probably just suppressing the warning would be enough.

**Comment by fommil** [comment]
We're going through the older bug reports that don't have a reproduction.

Nowadays, we close tickets that look like a known issue or don't provide the details requested by the template (which didn't exist when you reported this). The reason is to improve the quality of our issue tracker and to make it easier for contributors to help.

Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. We are happy to help you write an automated test exhibiting the bug, and discuss ideas on how to fix, read the http://ensime.org/contributing guide for more information.

We will leave this ticket open for a few weeks. If you can confirm it is a bug by giving us a **detailed** reproduction - or let us know that you're working on a fix - we will leave it open for longer.

Please read the http://ensime.org/getting_help guide to understand the steps that are now required prior to submitting a bug report. We recently rewrote almost all the documentation since this bug was initially reported and you might find some useful information in there.

**Comment by fommil** [comment]
I think i can create a repro for this with a macro. I just need to find the time.
