### ISSUE TITLE
very slow if ensime-server not up

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#822]
Sometimes I am reading sources or making changes to code that doesn't have an ENSIME server behind it (just check changes) and I noticed that moving the cursor and editing is really slow.

We must be doing something on every keypress that is expecting a result, even when there is no connected server or .ensime config for the project.

**Comment by jcazevedo** [comment]
I don't notice this if I have no ENSIME connection started. However, if I start ENSIME for a project and switch to another Scala buffer that has no connection to ENSIME, moving the cursor and editing becomes painfully slow. A quick profiling seems to relate this issue with `ensime-modeline-string`.

**Comment by aemoncannon** [comment]
Ah. I know what's wrong. ensime-modeline-string does a bunch of work to
determine which connection if any should be associated with the file. If a
connection is found, we cache it (see owning-connection-for-source file ..
I think), but if no connection is ever found, we continue to search each
time the modeline wants to repaint, which is a lot. This was recently
aggrevated by the addition of symlink aware searching, so now we're
actually hitting the disk on each failed search. Womp womp.

We don't want to cache the fact that a connection was not found, since we
sometimes want the connection to be found once ensime starts, but perhaps
could cache that a particular connection is no good... or something like
that...

**Comment by aemoncannon** [comment]
Another idea: memoize the file-truename function. That way we won't be
looking at the disk. I'm guessing that'll take care of the bulk of the
slowdown.

**Comment by aemoncannon** [comment]
Does this sort out the issue? https://github.com/ensime/ensime-emacs/pull/91

**Comment by fommil** [comment]
nope, doesn't speed it up :-(

As a workaround, I `M-x ensime-mode` to turn off ENSIME. It impacts me most when hacking around in the project build files, which don't have an ENSIME server attached.

**Comment by aemoncannon** [comment]
OK thanks. I think I know what's missing.
