### ISSUE TITLE
Refactoring failure: assertion failed: bad position: [2651:2615]

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#858]
@bjarkevad is seeing an issue during refactoring:

https://gist.github.com/bjarkevad/dfa2ab229c8316fceef5

The refactor request itself (inline local).

Things to do/confirm

1.  Scala version of project
2.  Minimised example 
3. Report to https://github.com/scala-ide/scala-refactoring and/or request a release of 0.6.3

**Comment by rorygraves** [comment]
I'm guessing its an edge case bug in the refactoring library - need to ascertain the shape of the refactor (its a commercial project so no immediate reproducible case.

**Comment by fommil** [comment]
https://github.com/bjarkevad/ensime-refactoring-bug

**Comment by fommil** [comment]
one thing to point out here: it looks like the starting position is **after** the ending position. Might be of use to upstream.

**Comment by fommil** [comment]
@bjarkevad is this still happening?

**Comment by fommil** [comment]
We're going through the older bug reports that don't have a reproduction.

Nowadays, we close tickets that look like a known issue or don't provide the details requested by the template (which didn't exist when you reported this). The reason is to improve the quality of our issue tracker and to make it easier for contributors to help.

Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. We are happy to help you write an automated test exhibiting the bug, and discuss ideas on how to fix, read the http://ensime.org/contributing guide for more information.

We will leave this ticket open for a few weeks. If you can confirm it is a bug by giving us a **detailed** reproduction - or let us know that you're working on a fix - we will leave it open for longer.

Please read the http://ensime.org/getting_help guide to understand the steps that are now required prior to submitting a bug report. We recently rewrote almost all the documentation since this bug was initially reported and you might find some useful information in there.
