### ISSUE TITLE
Consider adding sbt-buildinfo to build

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#894]
https://github.com/sbt/sbt-buildinfo

**Comment by fommil** [comment]
cool! We could convert that into an `EnsimeConfig` (assuming it doesn't mean that we need to run `updateClassifiers` every time we invoke `sbt` again, like before).

**Comment by rorygraves** [comment]
Need to revisit this - this would have picked up the 'ivy failed to pickup the latest version'
 pretty quickly

**Comment by fommil** [comment]
I'm not so sure about that. If ivy is borked, there isn't much we can do. Who's to say it was an ensime jar that was broken, or that the metadata even existed in the jar.

**Comment by rorygraves** [comment]
I'm sort of hoping the non-snapshot stuff actually works as designed

**Comment by fommil** [comment]
nope. and the thing that I find hilarious is that sbt uses ivy because ivy is supposed to have such a better model, and is so much more customisable.

So, turns out, if your company uses a completely custom ivy repository, sbt basically doesn't have a fsking clue what to do. Apparently, if the really flexible ivy definitions don't look identical to the maven central layout, it all blows up with exceptions. True Story.

**Comment by fommil** [comment]
@davegurnell this is another one for your talk

**Comment by davegurnell** [comment]
Crackin'! I shall put this to use on several projects!

It beats my "solution" to getting version information into the codebase:
https://github.com/davegurnell/versionit
