### ISSUE TITLE
Set externalResolvers for ensime-server updates

### ISSUE THREAD

**Issue by channingwalton** [ensime/ensime-server#969]
In our corporate world we have various firewall/proxy issues which requires us to set SBTs externalResolvers key.

We need to be set that for when Ensime uses set to update itself.

**Comment by fommil** [comment]
There are a couple of ways to tackle this, and the indecision about how far we want to go to address the problem is the reason this has not been fixed yet.

The emacs client generates a temporary project to download all the ensime-server jars and then generates a classpath file (which means subsequent starts don't need to resolve anything) https://github.com/ensime/ensime-emacs/blob/master/ensime-startup.el#L22

One possible approach is to add external resolvers (possible as the default) to be added here.

Another approach is to say that this is a deployment issue and that, actually, additional resolvers should be set on a per-user level, not a per-project level. In that case, you can set the resolvers in your `~/.sbt/0.13/global.sbt` and all projects will benefit.

Can you please try the latter first? And if that fails, edit your `ensime-startup.el` directly to add the resolvers you need.

If that works, then you're one of the lucky ones with an ivy proxy. If not, your environment might be a maven proxy which complicates matters. More below.

An additional problem is downloading of sbt itself. It turns out that **there is no portable way** to tell the sbt script where to look to download itself. However, it is possible to set the proxy for paulp's -sbt-extras` start script https://github.com/paulp/sbt-extras/blob/master/sbt by putting something like this in the root of your project:

```
-java-home
/usr/lib/jvm/jdk-8-oracle-x64
-sbt-launch-repo
http://nexus.mydomain.com:8081/nexus/content/groups/mirror/
```

(must be a newline at the end). Incidentally, this is also how to set the JDK on a per-project basis... don't trust setting anything in your sbt config files.

But back to that issue about ivy/maven. The only way to truly override the baked-in repositories in sbt is to have an additional `.jvmopts` file in the root of your project that looks like this:

```
-Xss2m
-Xmx8g
-XX:+UseConcMarkSweepGC
-Dsbt.repository.config=.sbt-repositories
```

with a corresponding `.sbt-repositories`

```
[repositories]
local
my-maven-proxy-releases: http://nexus.mycompany.com:8081/nexus/content/groups/mirror/
my-ivy-proxy-releases: http://nexus.mycompany.com:8081/nexus/content/groups/mirror/, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext]
```

So... I'm tempted to suggest that the process for fixing this should be:

1. try to add an external resolver to your global config. (if this doesn't work, but hacking the `ensime-startup.el` does work, then maybe we should have a config parameter for it)
2. `cd` into the temporary project that is created by `ensime-update`, create `.sbtopts`, `.jvmopts` and `sbt-repositories` that are relevant for your environment, and type `sbt saveClasspath`. Next time you type `ensime` for a project using that same version of scala it'll just startup.

One final thing, if you don't mirror the sonatype snapshots, then you'll have to grab the github repo, choose the branch for your version of scala, and issue an `sbt publishLocal`.

**Comment by fommil** [comment]
@jsuereth @eed3si9n do you have any advice beyond the above? (Standardising how to set `JAVA_HOME` and proxies would be a really great improvement for corporate environments that almost always require this to be set on both user and project levels)

**Comment by channingwalton** [comment]
Thanks I'll try some of the things you suggest, I may be some time …

**Comment by channingwalton** [comment]
Random thought, since this is running from Emacs, can Emacs's proxy settings be passed through to sbt? I set mine in site-start.el, although there is an issue of authorisation.

**Comment by jsuereth** [comment]
@fommil Not sure what the "additional problem" refers to for sbt scripts downloading themselves, as these are machine-installable packages which include one version of the launcher and should be able to launch previous version of sbt.  i.e. there is no download required to start the launcher, and the launcher exposes mechnaisms for proxy configuration, SO, you should be able to use a repositories file just fine.  AFAIK sbt-extras exists solely so that the script itself will also download the launcher.  There's actually potential ivy cache corruption issues that occur from upgrading/downgrading the launcher repeatedly, so we generally don't recommend that approach.  Best to always have a "newer" sbt-launch.jar and launch older builds with it.

@channingwalton sbt considers proxies a machine-level concern (not a project concern).  This is something which is relatively true, but e.g.  not true for laptops (where your proxies may change based on where the laptop is connected to internet).  However, we do have a things we may try to make it easier to handle proxy resolvers:

See: https://github.com/sbt/launcher/issues/6

Addtionally, @fommil's suggestion of .sbtops + .sbtrepositories is quite good right now.  If you see a discussion on sbt-dev, there was a more recent suggestion of allowing some of these properties to additionally be defined in project/build.properties (which configures the sbt launcher).   That would allow you to have project-specific repository configuration *and* user-specific configuration.

**Comment by fommil** [comment]
@jsuereth It would be ideal if there was a way to specify, in one place for a user, what the repository rules should be, with project specific overrides. It would also be incredibly helpful if the official script and paulp's script were reconciled.

**Comment by fommil** [comment]
@jsuereth `.sbtopts` and `.sbtrepositories` are project-level configurations as far as I was aware. Can they be placed in the home directory for user-level use?

**Comment by jsuereth** [comment]
`~/.sbt/repsoitories` is the default location.  As for unification, the suggestions to fix sbt-launcher would help here, as all the config would be readable from `project/build.properties` *or* `~/.sbt/repositories`.

**Comment by fommil** [comment]
@jsuereth that's very interesting, I didn't realise there was a default `~/.sbt/repositories` file. I think I'll use that myself.

Where can I submit a bug report that the `JAVA_HOME` (actually it should be trumped by `JDK_HOME`) is not correctly respected by `sbt`? The `javaHome` is set correctly, but `javac` is called on the `PATH` and therefore uses whatever the system default is.

**Comment by channingwalton** [comment]
Thanks all - I am attempting to digest. I've been unable to find a combination yet that works, but I haven't tried everything yet.

**Comment by fommil** [comment]
What do you do for your own project? Do you have access to sonatype snapshots?

**Comment by channingwalton** [comment]
We don't have access to snapshots via the company nexus. The projects have their own sbtopts etc which are shared, I can't fiddle with those.

I can set proxy config in emacs/shells, and my own settings in ~/.sbt, its just a question of casting the right magic somewhere.

**Comment by fommil** [comment]
Ok then you need to grab the git repo for ensime-server until 1.0 is released and publishLocal.

**Comment by channingwalton** [comment]
Ok cool.

**Comment by fommil** [comment]
You'll miss out on continual releases, which is unfortunate because there is a performance issue at the moment that we'll fix soon.

**Comment by channingwalton** [comment]
no problem, I'll keep pulling.

**Comment by fommil** [comment]
This issue was moved to ensime/ensime-emacs#154
