### ISSUE TITLE
prepare/exec refactor should be one call...

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-server#996]
... that simply returns the diff of what should happen.

This places the responsibility of the edit (and undos) in the hands of the editor.

**Comment by rorygraves** [comment]
@fommil and I discussed this idea yesterday.  The current refactor undo is very fragile if, between doing refactor and undo you make other non-refactor edits.  The idea is by supplying the information to the client 'these 4 files need these changes', the client can insert them into its undo stack allowing IntelliJ style 'are you sure you want to undo 'refactor name' operation?'

2.0 feature as it requires a non-trivial amount of client side work otherwise we break the existing refactoring support. 

@fommil Maybe we should just remove the 'undo stack' within the server for 1.0?

**Comment by fommil** [comment]
Yeah, it's complicated and I wouldn't trust it over my VCS anyway.

**Comment by aemoncannon** [comment]
+1

**Comment by fommil** [comment]
this has been done!
